#--------------------------------------------------------------
# GitHubAWDeploy html_App to AWS EB
#
# Version      Date        Info
# 1.1          2021        Init Version

name: ci-cd-pipeline-to-aws-elb
env :
  EB_S3_BUCKET_NAME     : "serjio-flask-app-packages"
  EB_APP_NAME           : "GitHub-Actions-to-AWS"
  EB_ENVIRONMENT_NAME   : "Githubactionstoaws-env"
  DEPLOY_PACKAGE_NAME   : "py_app_${{ github.sha }}.zip"
  AWS_REGION_NAME       : "us-west-2"

on: 
  push:
    branches: 
      - master

jobs:
  ci_part:
    runs-on: amazon-linux-2/3.1.5

    steps:
    - name: Git clone repo to test
      uses: actions/checkout@v1.1
       
    - name: Create zip deployment package
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      
    




